require 'launch'
require 'options'

spec 'plugins.treesitter'
spec 'plugins.mason'
spec 'plugins.lspconfig'
spec 'plugins.whichkey'
spec 'plugins.devicons'
spec 'plugins.telescope'
spec 'plugins.autopairs'
spec 'plugins.project'
spec 'plugins.toggleterm'
spec 'plugins.oil'
spec 'plugins.neozoom'
spec 'plugins.illuminate'
spec 'plugins.cmp'
spec 'plugins.comment'
spec 'plugins.navic'
spec 'plugins.navbuddy'
spec 'plugins.github-theme'
-- spec 'plugins.colorscheme'
spec 'plugins.debugging'
spec 'plugins.vimtex'
spec 'plugins.markdown'
spec 'plugins.obsidian'
spec 'plugins.dotnet'
spec 'plugins.auto-dark-mode'

require 'plugins.lazy'

